name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Сделать gradlew исполняемым
      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build & Test
        run: ./gradlew build --stacktrace --console=plain
